version: 2
models:
  - name: stg_orders
    description: "cleaned and transformed orders data from csv file"
    columns:
      - name: order_id
        description: "The unique identifier for each order placed."
        tests: [ not_null, unique ]
      - name: user_id
        description: "The unique identifier for the user who placed the order."
        tests: [ not_null ]
      - name: order_date
        description: "The date when the order was placed."
        tests: [ not_null ]

  - name: stg_users
    description: "cleaned  and type casted users data from csv file"
    columns:
      - name: user_id
        description: "The unique identifier for each user."
        tests: [ not_null, unique ]
      - name: signup_date
        description: "The date when the user signed up."
        tests: [ not_null ]
      - name: city
        description: "The city where the user is located."
        tests: [ not_null ]

  - name: stg_payments
    description: "cleaned and transformed payments data from csv file."
    columns:
      - name: payment_id
        description: "The unique identifier for each payment."
        tests: [ not_null, unique ]
      - name: order_id
        description: "The unique identifier for the order associated with the payment."
        tests: [ not_null ]
      - name: payment_method
        description: "The method used for the payment (e.g card, UPI)."
      - name: payment_status
        description: "The status of the payment (e.g success,failed)."


  - name: orders_joining
    description: "Joined and merged data from orders, users, and payments staging tables by taking only relevant columns and reducing name ambiguity"

  - name: daily_revenue
    description: "final output table calculating daily revenue per city."
    columns:
      - name: order_date
        description: "The date when the orders were placed."
        tests: [ not_null ]
      - name: city
        description: "The city where the users are located."  
      - name: total_revenue
        description: "The total revenue generated."
      - name: refunded_amount
        description: "The total amount refunded."
      
